name: "❓ Question"
description: Ask a question about usage, configuration, or troubleshooting.
title: "[QUESTION] <short summary>"
labels: ["question", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        For faster, chat-style help, try Discord: https://discord.gg/your-invite
  - type: textarea
    id: question
    attributes:
      label: Your question
      description: What are you trying to achieve? What have you tried?
    validations:
      required: true
  - type: input
    id: extension_version
    attributes:
      label: Extension version
      placeholder: v1.0.0
  - type: input
    id: vscode_version
    attributes:
      label: VS Code version
      placeholder: "1.93.0"
  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: "macOS 14.5 / Windows 11 / Ubuntu 22.04"
  - type: textarea
    id: context
    attributes:
      label: Context / logs / screenshots
      description: Share any details that could help us help you.
